name: Test goreleaser

on:
  push:
    branches:
      - main

jobs:
  the_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Chainloop Open Source Repository
      uses: actions/checkout@v4
      with:
        repository: chainloop-dev/chainloop
        path: chainloop
        fetch-depth: 0
      