name: Test goreleaser

on:
  push:
    branches:
      - main


permissions:
  contents: write # required for goreleaser to upload the release assets
  packages: write # to push container images
  
jobs:
  the_build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Goreleaser Base Repository
      uses: actions/checkout@v4
      with:
        repository: javirln/goreleaser
        path: base-repo

    - name: Checkout Chainloop Open Source Repository
      uses: actions/checkout@v4
      with:
        repository: chainloop-dev/chainloop
        ref: bb1159cc3b96f85f705770c9597377822d6bbb6b
        path: chainloop
        fetch-depth: 0

    - name: ls
      run: ls -la

    - name: Setup qemu
      id: qemu
      uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0

    - name: Build Chainloop Windows CLI
      uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # v3.2.0
      with:
        args: build --clean --config ../base-repo/.goreleaser.yaml --snapshot
        workdir: chainloop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      