name: build-attested-image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create checksum file
        run: |
          echo "8881c1a89650c9fa9d06fee4ff6fb898cf931c4255663ce801d4474549a60fc1  index.docker.io/bitnami/wordpress" > sha256.txt
          echo "b35cac45090f87b8be132aa2aaa02db65c498a85b79a420f261d0a502792bc04  index.docker.io/bitnami/nats" >> sha256.txt

      - name: Attest
        uses: actions/attest-build-provenance@v2
        id: slsa-attest
        with:
          subject-checksums: sha256.txt
          push-to-registry: false

      - name: Cat attestation
        run: |
          cat {{ steps.slsa-attest.outputs.bundle-path }}
