name: build-attested-image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/chainloop-dev/platform/backend
      MIGRATION_IMAGE_NAME: ghcr.io/chainloop-dev/platform/backend-migrations

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Generate Container image checksum file for SLSA attestation
        run: |
          checksum_file="subjects-checksum.txt"
          touch "$checksum_file"

          # First the binaries
          binaries=$(cat dist/artifacts.json | jq -r '.[] | select(.type=="Binary") | select(.name=="chainloop"| not) | "\(.path) \(.name)"')
          echo "$binaries" | while IFS= read -r entry; do
            # Extract the path and name from the entry
            path=$(echo "$entry" | awk '{print $1}')
            # Calculate the checksum of the file
            checksum=$(sha256sum "$path" | awk '{print $1}')
            # Get the name from the entry
            name=$(echo "$entry" | awk '{print $2}')
            # Add it to the checksum file
            echo "$checksum *$name" >> $checksum_file
          done


      - uses: actions/attest-build-provenance@619dbb2e03e0189af0c55118e7d3c5e129e99726
        with:
          subject-checksums: subjects-checksum.txt

      - name: Cat checksum
        run: |
          cat subjects-checksum.txt
